import type { Product, Category } from "@/types";

export const categories: Category[] = [
  { id: "1", name: "狗狗专区", slug: "dog", description: "给狗狗最好的陪伴", imageUrl: null, children: [] },
  { id: "2", name: "猫咪专区", slug: "cat", description: "猫咪的精致生活", imageUrl: null, children: [] },
  { id: "3", name: "小宠专区", slug: "small", description: "仓鼠·兔子·鸟类用品", imageUrl: null, children: [] },
  { id: "4", name: "食品营养", slug: "food", description: "天然健康宠物食品", imageUrl: null, children: [] },
  { id: "5", name: "出行装备", slug: "travel", description: "外出旅行必备", imageUrl: null, children: [] },
  { id: "6", name: "美容护理", slug: "grooming", description: "洗护美容用品", imageUrl: null, children: [] },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "柔软宠物窝垫 — 暖阳系列",
    slug: "warm-pet-bed",
    description: "采用亲肤绒布面料，加厚 PP 棉填充，给爱宠一个温暖的港湾。底部防滑颗粒设计，防止移位。全垫可拆卸机洗，方便清洁。适合中小型犬及猫咪。\n\n产品特点：\n· 双面可用 — 一面绒布温暖，一面透气棉麻\n· 加厚边缘 — 提供头部支撑与安全感\n· 隐藏式拉链 — 美观且不易被宠物咬坏\n· 多色可选 — 暖黄 / 浅灰 / 燕麦",
    shortDesc: "亲肤绒布 · 加厚填充 · 可拆卸机洗",
    price: 168,
    compareAtPrice: 238,
    stock: 50,
    sku: "BED001",
    isActive: true,
    isFeatured: true,
    categoryId: "1",
    category: categories[0],
    brand: "Nonta",
    petType: "dog",
    images: [
      { id: "img1a", productId: "p1", url: "https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=600&q=80", alt: "暖黄宠物窝垫", sortOrder: 0, isPrimary: true },
      { id: "img1b", productId: "p1", url: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&q=80", alt: "灰色宠物窝垫", sortOrder: 1, isPrimary: false },
    ],
    variants: [
      { id: "v1", productId: "p1", name: "S 号 · 暖黄", sku: "BED001-S-Y", price: 138, stock: 20, isActive: true },
      { id: "v2", productId: "p1", name: "M 号 · 暖黄", sku: "BED001-M-Y", price: 168, stock: 20, isActive: true },
      { id: "v3", productId: "p1", name: "L 号 · 浅灰", sku: "BED001-L-G", price: 208, stock: 10, isActive: true },
    ],
    reviews: [
      { id: "r1", userId: "u1", productId: "p1", rating: 5, title: "我家狗狗一拿到就躺进去了", content: "面料特别柔软，底部防滑做得很好，洗了一次也没有变形。推荐！", images: [], createdAt: "2024-06-15" },
      { id: "r2", userId: "u2", productId: "p1", rating: 4, title: "做工精致", content: "颜色很正，手感很好。L 号对于 30 斤的柯基刚好。", images: [], createdAt: "2024-06-10" },
    ],
    createdAt: "2024-01-15",
  },
  {
    id: "p2",
    name: "智能循环宠物饮水机",
    slug: "smart-pet-fountain",
    description: "四层过滤系统（活性炭 + 离子交换树脂 + 微孔过滤棉 + 不锈钢滤网），2.5L 大容量满足多宠家庭需求。超静音水泵，流动活水吸引宠物饮水，有效预防泌尿系统疾病。\n\n产品特点：\n· 循环活水 — 模拟自然溪流，宠物更爱喝\n· 四层过滤 — 去除毛发、杂质、异味\n· 超静音设计 — 夜间不影响睡眠\n· 透明水窗 — 水位一目了然\n· USB 供电 — 安全低压，节能环保",
    shortDesc: "四层过滤 · 循环活水 · 静音水泵 · 2.5L 容量",
    price: 258,
    compareAtPrice: 358,
    stock: 30,
    sku: "WTR001",
    isActive: true,
    isFeatured: true,
    categoryId: "2",
    category: categories[1],
    brand: "Nonta",
    petType: "cat",
    images: [
      { id: "img2a", productId: "p2", url: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&q=80", alt: "智能宠物饮水机", sortOrder: 0, isPrimary: true },
    ],
    variants: [],
    reviews: [
      { id: "r3", userId: "u3", productId: "p2", rating: 5, title: "猫咪喝水量明显增加了", content: "以前猫主子不爱喝水，现在一天能喝大半箱！声音也很轻，完全不会吓到猫咪。", images: [], createdAt: "2024-06-20" },
    ],
    createdAt: "2024-02-01",
  },
  {
    id: "p3",
    name: "天然牛皮咬胶 — 洁齿磨牙棒",
    slug: "natural-chew-stick",
    description: "100% 天然牛皮制作，无添加、无漂白，安全可食用。高密度压制工艺，耐咬不掉渣。有效清洁牙齿、去除牙垢，同时缓解换牙期和独处焦虑。\n\n适用：中大型犬日常磨牙洁齿",
    shortDesc: "天然牛皮 · 洁齿护龈 · 耐咬不掉渣",
    price: 48,
    compareAtPrice: 68,
    stock: 100,
    sku: "CHEW001",
    isActive: true,
    isFeatured: true,
    categoryId: "1",
    category: categories[0],
    brand: "Nonta",
    petType: "dog",
    images: [
      { id: "img3a", productId: "p3", url: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80", alt: "天然牛皮咬胶", sortOrder: 0, isPrimary: true },
    ],
    variants: [
      { id: "v4", productId: "p3", name: "S 号 · 小型犬", sku: "CHEW001-S", price: 38, stock: 50, isActive: true },
      { id: "v5", productId: "p3", name: "M 号 · 中型犬", sku: "CHEW001-M", price: 48, stock: 30, isActive: true },
      { id: "v6", productId: "p3", name: "L 号 · 大型犬", sku: "CHEW001-L", price: 58, stock: 20, isActive: true },
    ],
    reviews: [],
    createdAt: "2024-03-01",
  },
  {
    id: "p4",
    name: "猫咪太空舱外出背包",
    slug: "cat-space-backpack",
    description: "360° 透明太空舱设计，让猫咪在出行时也能观察外界。三面透气网布 + 顶部透气窗，空气流通不闷热。加厚柔软内垫，可拆卸清洗。配备安全锁扣和可拆遮光罩。\n\n适用：体重 8kg 以内的猫咪及小型犬",
    shortDesc: "透明太空舱 · 透气不闷 · 安全锁扣",
    price: 198,
    compareAtPrice: 278,
    stock: 25,
    sku: "BAG001",
    isActive: true,
    isFeatured: true,
    categoryId: "5",
    category: categories[4],
    brand: "Nonta",
    petType: "cat",
    images: [
      { id: "img4a", productId: "p4", url: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&q=80", alt: "太空舱外出背包", sortOrder: 0, isPrimary: true },
    ],
    variants: [],
    reviews: [
      { id: "r4", userId: "u4", productId: "p4", rating: 4, title: "颜值超高", content: "做工精致，背着也很舒服。猫咪一开始有点紧张，用了几次就习惯了，现在会自己钻进去。", images: [], createdAt: "2024-05-20" },
    ],
    createdAt: "2024-04-01",
  },
  {
    id: "p5",
    name: "自洁式宠物去毛梳",
    slug: "self-cleaning-brush",
    description: "不锈钢弯针梳齿，深入毛发底层轻松去除浮毛与死毛。一键退毛设计，按下按钮梳齿自动收回，毛发轻松清理。人体工学防滑手柄，长时间梳理不累手。\n\n适用：猫犬通用，长毛短毛均可",
    shortDesc: "不锈钢弯针 · 一键退毛 · 猫犬通用",
    price: 78,
    compareAtPrice: 108,
    stock: 80,
    sku: "BRUSH001",
    isActive: true,
    isFeatured: false,
    categoryId: "6",
    category: categories[5],
    brand: "Nonta",
    petType: "cat",
    images: [
      { id: "img5a", productId: "p5", url: "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=600&q=80", alt: "宠物去毛梳", sortOrder: 0, isPrimary: true },
    ],
    variants: [],
    reviews: [
      { id: "r5", userId: "u5", productId: "p5", rating: 5, title: "退毛太方便了", content: "一按就干净，不用一根根用手拔。长毛布偶猫的救星！", images: [], createdAt: "2024-06-01" },
    ],
    createdAt: "2024-05-01",
  },
  {
    id: "p6",
    name: "宠物益智漏食球",
    slug: "puzzle-food-ball",
    description: "可调节出食孔大小，控制漏食速度，培养宠物慢食习惯，预防消化不良和胃扭转。漏食过程锻炼宠物智力与耐心，缓解独处焦虑。食品级 ABS 材质，安全无毒。\n\n适用：犬猫通用",
    shortDesc: "可调漏食速度 · 锻炼智力 · 缓解焦虑",
    price: 58,
    compareAtPrice: null,
    stock: 60,
    sku: "TOY001",
    isActive: true,
    isFeatured: false,
    categoryId: "1",
    category: categories[0],
    brand: "Nonta",
    petType: "dog",
    images: [
      { id: "img6a", productId: "p6", url: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80", alt: "宠物益智漏食球", sortOrder: 0, isPrimary: true },
    ],
    variants: [],
    reviews: [],
    createdAt: "2024-06-01",
  },
  {
    id: "p7",
    name: "反光安全宠物牵引绳",
    slug: "reflective-leash",
    description: "高密度尼龙编织材质，耐磨抗拉，结实耐用。手柄软垫设计，长时间握持不勒手。夜光反光条全绳贯穿，夜间出行 200 米可见，保障安全。长度可自由调节，适应不同场景需求。",
    shortDesc: "反光安全 · 长度可调 · 舒适握把",
    price: 88,
    compareAtPrice: 128,
    stock: 45,
    sku: "LSH001",
    isActive: true,
    isFeatured: false,
    categoryId: "1",
    category: categories[0],
    brand: "Nonta",
    petType: "dog",
    images: [
      { id: "img7a", productId: "p7", url: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=600&q=80", alt: "反光牵引绳", sortOrder: 0, isPrimary: true },
      { id: "img7b", productId: "p7", url: "https://images.unsplash.com/photo-1558929996-da64b8580a38?w=600&q=80", alt: "牵引绳使用场景", sortOrder: 1, isPrimary: false },
    ],
    variants: [
      { id: "v7", productId: "p7", name: "红色 1.2m", sku: "LSH001-R-120", price: 88, stock: 20, isActive: true },
      { id: "v8", productId: "p7", name: "黑色 1.5m", sku: "LSH001-B-150", price: 98, stock: 25, isActive: true },
    ],
    reviews: [],
    createdAt: "2024-06-15",
  },
  {
    id: "p8",
    name: "天然豆腐猫砂 — 绿茶除臭型",
    slug: "tofu-cat-litter",
    description: "天然豆腐纤维制成，1.5mm 细颗粒，快速结团、轻松铲出。添加天然绿茶精华，持久除臭抑菌。99% 无尘配方，保护猫咪呼吸道。可直接冲入马桶，环保降解。\n\n每袋 2.5kg，约可用 2-3 周",
    shortDesc: "天然豆腐 · 速结团 · 绿茶除臭 · 可冲厕所",
    price: 38,
    compareAtPrice: null,
    stock: 200,
    sku: "LIT001",
    isActive: true,
    isFeatured: true,
    categoryId: "2",
    category: categories[1],
    brand: "Nonta",
    petType: "cat",
    images: [
      { id: "img8a", productId: "p8", url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80", alt: "豆腐猫砂", sortOrder: 0, isPrimary: true },
      { id: "img8b", productId: "p8", url: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&q=80", alt: "猫咪使用场景", sortOrder: 1, isPrimary: false },
    ],
    variants: [
      { id: "v9", productId: "p8", name: "2.5kg 装", sku: "LIT001-2.5", price: 38, stock: 100, isActive: true },
      { id: "v10", productId: "p8", name: "5kg 装 (2袋)", sku: "LIT001-5", price: 68, stock: 100, isActive: true },
    ],
    reviews: [
      { id: "r6", userId: "u6", productId: "p8", rating: 5, title: "最好用的猫砂没有之一", content: "结团速度超快，基本没有粉尘。除臭效果也很棒！", images: [], createdAt: "2024-06-22" },
      { id: "r7", userId: "u7", productId: "p8", rating: 5, title: "会一直回购", content: "可以直接冲厕所太方便了，再也不用每天下楼扔垃圾。", images: [], createdAt: "2024-06-25" },
    ],
    createdAt: "2024-05-15",
  },
  {
    id: "p9",
    name: "可折叠宠物航空箱",
    slug: "foldable-carrier",
    description: "高韧性 PP 材质，抗压耐摔。三面透气孔 + 顶部天窗，通风不闷。无需工具即可快速折叠收纳，节省 70% 空间。符合 IATA 航空运输标准。两侧安全锁扣，防止宠物意外逃出。\n\n适用：8kg 以内猫犬",
    shortDesc: "折叠收纳 · 航空标准 · 三面透气",
    price: 238,
    compareAtPrice: 328,
    stock: 30,
    sku: "CRT001",
    isActive: true,
    isFeatured: true,
    categoryId: "5",
    category: categories[4],
    brand: "Nonta",
    petType: "cat",
    images: [
      { id: "img9a", productId: "p9", url: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&q=80", alt: "折叠航空箱", sortOrder: 0, isPrimary: true },
    ],
    variants: [],
    reviews: [],
    createdAt: "2024-06-15",
  },
  {
    id: "p10",
    name: "宠物专用温和沐浴露",
    slug: "gentle-pet-shampoo",
    description: "天然植物配方，pH 值平衡，温和不刺激。添加燕麦精华与芦荟提取物，滋润毛发、舒缓皮肤。无硅油、无酒精、无人工香精。泡沫细腻易冲洗，洗后毛发蓬松顺滑。\n\n适用：犬猫通用",
    shortDesc: "天然植物 · pH 平衡 · 无刺激 · 猫犬通用",
    price: 68,
    compareAtPrice: 98,
    stock: 80,
    sku: "SHMP001",
    isActive: true,
    isFeatured: false,
    categoryId: "6",
    category: categories[5],
    brand: "Nonta",
    petType: "dog",
    images: [
      { id: "img10a", productId: "p10", url: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&q=80", alt: "宠物沐浴露", sortOrder: 0, isPrimary: true },
    ],
    variants: [],
    reviews: [],
    createdAt: "2024-06-20",
  },
];

// Banner — 翻译自 nonta 日文原文
export const banners = [
  {
    title: "与宠物一起\n自由与温暖",
    subtitle: "以水獭 Nonta 为灵感\n将充满爱意的产品送到你手中",
    bgClass: "bg-gradient-to-br from-stone-50 to-stone-100",
    textColor: "text-stone-800",
  },
  {
    title: "人与宠物的\n温柔时光",
    subtitle: "Nonta 珍视人与宠物共同度过的每一个幸福瞬间\n功能与美的融合，为爱宠带来最贴心的呵护",
    bgClass: "bg-gradient-to-br from-stone-100 to-amber-50",
    textColor: "text-stone-800",
  },
];
