import type { Product, Category } from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "狗狗专区",
    slug: "dog",
    description: "给狗狗最好的爱",
    imageUrl: null,
    children: [],
  },
  {
    id: "2",
    name: "猫咪专区",
    slug: "cat",
    description: "猫咪的精致生活",
    imageUrl: null,
    children: [],
  },
  {
    id: "3",
    name: "鸟类专区",
    slug: "bird",
    description: "鸟类用品",
    imageUrl: null,
    children: [],
  },
  {
    id: "4",
    name: "小宠专区",
    slug: "small",
    description: "兔兔、仓鼠等小宠用品",
    imageUrl: null,
    children: [],
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "柔软宠物窝垫 — 暖阳系列",
    slug: "warm-pet-bed",
    description:
      "采用亲肤绒布面料，加厚填充，给爱宠一个温暖的港湾。底部防滑设计，不易移动。可拆卸清洗。",
    shortDesc: "亲肤绒布，加厚柔软，给宠物一个温暖的梦",
    price: 168,
    compareAtPrice: 238,
    stock: 50,
    sku: "BED001",
    isActive: true,
    isFeatured: true,
    categoryId: "1",
    category: categories[0],
    brand: "Nonta",
    petType: "dog",
    images: [
      {
        id: "img1",
        productId: "p1",
        url: "https://images.unsplash.com/photo-1541599468348-4ed0312aac1e?w=600&q=80",
        alt: "柔软宠物窝垫 — 暖黄",
        sortOrder: 0,
        isPrimary: true,
      },
      {
        id: "img2",
        productId: "p1",
        url: "https://images.unsplash.com/photo-1544568100-847a948585b9?w=600&q=80",
        alt: "宠物窝垫 — 灰色",
        sortOrder: 1,
        isPrimary: false,
      },
    ],
    variants: [
      { id: "v1", productId: "p1", name: "S号 — 暖黄", sku: "BED001-S-Y", price: 138, stock: 20, isActive: true },
      { id: "v2", productId: "p1", name: "M号 — 暖黄", sku: "BED001-M-Y", price: 168, stock: 20, isActive: true },
      { id: "v3", productId: "p1", name: "L号 — 灰色", sku: "BED001-L-G", price: 208, stock: 10, isActive: true },
    ],
    reviews: [
      { id: "r1", userId: "u1", productId: "p1", rating: 5, title: "我家狗狗超喜欢", content: "材质很柔软，底部防滑特别好，洗了一次也不变形。", images: [], createdAt: "2024-06-15" },
      { id: "r2", userId: "u2", productId: "p1", rating: 4, title: "质量不错", content: "做工精细，颜色也很正。就是L号对大型犬来说还是有点小了。", images: [], createdAt: "2024-06-10" },
    ],
    createdAt: "2024-01-15",
  },
  {
    id: "p2",
    name: "智能宠物饮水机",
    slug: "smart-pet-fountain",
    description:
      "四层过滤系统，2L大容量，静音水泵，流动活水吸引宠物多喝水。有效预防泌尿系统疾病。",
    shortDesc: "活水循环，四层过滤，让爱宠爱上喝水",
    price: 258,
    compareAtPrice: 358,
    stock: 30,
    sku: "WTR001",
    isActive: true,
    isFeatured: true,
    categoryId: "2",
    category: categories[1],
    brand: "Nonta",
    petType: "cat",
    images: [
      {
        id: "img3",
        productId: "p2",
        url: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&q=80",
        alt: "智能宠物饮水机",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [],
    reviews: [
      { id: "r3", userId: "u3", productId: "p2", rating: 5, title: "猫咪喝水量明显增加", content: "以前猫咪不爱喝水，现在每天都主动去喝！", images: [], createdAt: "2024-06-20" },
    ],
    createdAt: "2024-02-01",
  },
  {
    id: "p3",
    name: "天然牛皮咬胶 — 洁齿磨牙棒",
    slug: "natural-chew-stick",
    description:
      "100%天然牛皮制作，无添加，安全可食用。有效清洁牙齿，缓解换牙期不适。适合中大型犬。",
    shortDesc: "天然牛皮，洁齿护龈，狗狗最爱",
    price: 48,
    compareAtPrice: 68,
    stock: 100,
    sku: "CHEW001",
    isActive: true,
    isFeatured: true,
    categoryId: "1",
    category: categories[0],
    brand: "Nonta",
    petType: "dog",
    images: [
      {
        id: "img4",
        productId: "p3",
        url: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
        alt: "天然牛皮咬胶",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v4", productId: "p3", name: "S号 — 小型犬", sku: "CHEW001-S", price: 38, stock: 50, isActive: true },
      { id: "v5", productId: "p3", name: "M号 — 中型犬", sku: "CHEW001-M", price: 48, stock: 30, isActive: true },
      { id: "v6", productId: "p3", name: "L号 — 大型犬", sku: "CHEW001-L", price: 58, stock: 20, isActive: true },
    ],
    reviews: [],
    createdAt: "2024-03-01",
  },
  {
    id: "p4",
    name: "猫咪太空舱外出背包",
    slug: "cat-space-backpack",
    description:
      "透明太空舱设计，让猫咪可以观察外界。透气网面，舒适内垫。带安全锁扣和可拆式遮光罩。",
    shortDesc: "透明太空舱，带猫咪看世界",
    price: 198,
    compareAtPrice: 278,
    stock: 25,
    sku: "BAG001",
    isActive: true,
    isFeatured: true,
    categoryId: "2",
    category: categories[1],
    brand: "Nonta",
    petType: "cat",
    images: [
      {
        id: "img5",
        productId: "p4",
        url: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&q=80",
        alt: "猫咪太空舱背包",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [],
    reviews: [
      { id: "r4", userId: "u4", productId: "p4", rating: 4, title: "颜值很高", content: "做工很精致，猫咪刚开始有点紧张后来就喜欢了，推荐！", images: [], createdAt: "2024-05-20" },
    ],
    createdAt: "2024-04-01",
  },
  {
    id: "p5",
    name: "宠物去毛梳 — 自洁一键退毛",
    slug: "self-cleaning-brush",
    description:
      "不锈钢弯针梳齿，深入毛发底层。一键退毛设计，按下按钮即可清理梳齿。适用于所有毛发类型的猫咪和狗狗。",
    shortDesc: "不锈钢弯针，一键退毛，梳毛变简单",
    price: 78,
    compareAtPrice: 108,
    stock: 80,
    sku: "BRUSH001",
    isActive: true,
    isFeatured: false,
    categoryId: "2",
    category: categories[1],
    brand: "Nonta",
    petType: "cat",
    images: [
      {
        id: "img6",
        productId: "p5",
        url: "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=600&q=80",
        alt: "宠物去毛梳",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [],
    reviews: [
      { id: "r5", userId: "u5", productId: "p5", rating: 5, title: "退毛太方便了", content: "一按就干净，长毛猫必备！", images: [], createdAt: "2024-06-01" },
    ],
    createdAt: "2024-05-01",
  },
  {
    id: "p6",
    name: "宠物益智漏食球 — 慢食趣味玩具",
    slug: "puzzle-food-ball",
    description:
      "可调节出食孔大小，控制漏食速度。促进宠物慢食习惯，防止狼吞虎咽。同时锻炼宠物智力和耐心。",
    shortDesc: "边玩边吃，锻炼智力，培养慢食习惯",
    price: 58,
    compareAtPrice: null,
    stock: 60,
    sku: "TOY001",
    isActive: true,
    isFeatured: false,
    categoryId: "1",
    category: categories[0],
    brand: "Nonta",
    petType: "dog",
    images: [
      {
        id: "img7",
        productId: "p6",
        url: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
        alt: "宠物益智漏食球",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [],
    reviews: [],
    createdAt: "2024-06-01",
  },
  {
    id: "p7",
    name: "可调节宠物牵引绳 — 反光安全款",
    slug: "reflective-leash",
    description:
      "尼龙编织材质，坚固耐用。手柄软垫设计，握持舒适。带反光条，夜间出行更安全。长度可调节。",
    shortDesc: "反光安全，可调长短，舒适握把",
    price: 88,
    compareAtPrice: 128,
    stock: 45,
    sku: "LSH001",
    isActive: true,
    isFeatured: false,
    categoryId: "1",
    category: categories[0],
    brand: "Nonta",
    petType: "dog",
    images: [
      {
        id: "img8",
        productId: "p7",
        url: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=600&q=80",
        alt: "宠物牵引绳",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v7", productId: "p7", name: "红色 — 1.2m", sku: "LSH001-R-120", price: 88, stock: 20, isActive: true },
      { id: "v8", productId: "p7", name: "黑色 — 1.5m", sku: "LSH001-B-150", price: 98, stock: 25, isActive: true },
    ],
    reviews: [],
    createdAt: "2024-06-15",
  },
  {
    id: "p8",
    name: "天然豆腐猫砂 — 绿茶除臭型",
    slug: "tofu-cat-litter",
    description:
      "天然豆腐纤维制成，快速结团，轻松铲出。添加绿茶精华，有效除臭。可直接冲厕所，环保无尘。",
    shortDesc: "天然豆腐，速结团，绿茶除臭，可冲厕所",
    price: 38,
    compareAtPrice: null,
    stock: 200,
    sku: "LIT001",
    isActive: true,
    isFeatured: true,
    categoryId: "2",
    category: categories[1],
    brand: "Nonta",
    petType: "cat",
    images: [
      {
        id: "img9",
        productId: "p8",
        url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
        alt: "天然豆腐猫砂",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v9", productId: "p8", name: "2.5kg装", sku: "LIT001-2.5", price: 38, stock: 100, isActive: true },
      { id: "v10", productId: "p8", name: "5kg装", sku: "LIT001-5", price: 68, stock: 100, isActive: true },
    ],
    reviews: [
      { id: "r6", userId: "u6", productId: "p8", rating: 5, title: "最好用的猫砂", content: "结团快，基本没有粉尘，除臭效果也很好！", images: [], createdAt: "2024-06-22" },
      { id: "r7", userId: "u7", productId: "p8", rating: 5, title: "会一直回购", content: "可以冲厕所太方便了，再也不用拎垃圾袋下楼。", images: [], createdAt: "2024-06-25" },
    ],
    createdAt: "2024-05-15",
  },
];

// Banner 数据
export const banners = [
  {
    title: "宠物与人的温暖时光",
    subtitle: "用心挑选每件物品\n让爱与温暖陪伴每一天",
    bgClass: "bg-gradient-to-r from-[#F8F5F0] to-[#F2E9E2]",
    textColor: "text-[#8C7355]",
  },
  {
    title: "夏日清凉季",
    subtitle: "全场满199减20\n新用户注册领取9折券",
    bgClass: "bg-gradient-to-r from-[#EEEAE7] to-[#F5F1EB]",
    textColor: "text-[#6B5A45]",
  },
];
